# Generated by Django 5.0 on 2024-01-03 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational', models.BooleanField(default=True)),
                ('in_maintenance', models.BooleanField(default=False)),
                ('current_floor', models.IntegerField(default=1)),
                ('moving_up', models.BooleanField(default=False)),
                ('door_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_floor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevators.elevator')),
            ],
        ),
    ]
